### PR TITLE
bump logrus, go 1.17, enable M1 mac support

### PR DESCRIPTION
**Pull request by iameli**
Bumped logrus to v1.8.1. They're very committed to no breaking changes so this shouldn't change much.

Importantly, this includes a transitive dependency bump of `golang.org/x/sys` to `v0.0.0-20220520151302-bc2c85ada10a`, which is a version that supports M1 arm64 macs. We've tested and it appears to work very well, enabling Drone to run builds on M1 Macs!

EDIT: Also bumps the CI golang to 1.17; Go 1.12 didn't support M1 macs.

### CODE REVIEW

**Review by tphoney — CHANGES_REQUESTED** [review]
Hey @iameli you bumped the go version in the build file, but not in the go.mod. Otherwise this pr looks Brilliant 👍

**Comment by iameli** [comment]
@tphoney Got it, will do. When I upgrade that to Go 1.17, it prompts me that `go mod tidy` is necessary:
```
▶ scripts/build.sh
+ go build -o release/native/drone-runner-exec
go: updates to go.mod needed; to update it:
	go mod tidy
```

When I run that, the build works but it removes [all of the unused versions of github.com/drone/runner-go](https://github.com/drone-runners/drone-runner-exec/blob/8dfa5590d4cf42bf650a9f1705baa0c3ba8692a6/go.sum#L32-L93), among other things. I don't 100% understand go.sum; is it best practice to have them archived there or is it okay to remove them?

**Comment by iameli** [comment]
Went ahead and ran `go mod tidy` and it resulted in https://github.com/drone-runners/drone-runner-exec/pull/7/commits/c3104ba93ddc697bd3a505250f8f43a2299cc50c - should work well if that's what we're going for!

**Comment by tphoney** [comment]
thanks @iameli great work. MERGED 👍

**Comment by FabianTerhorst** [comment]
Is a new build planned soon to provide the m1 prebuild binary?

**Comment by iameli** [comment]
@FabianTerhorst If you need one I uploaded a prerelease build here, but would love an official one too! https://github.com/livepeer/drone-runner-exec/releases/tag/v1.0.0-beta.9-8-g1ada187

**Comment by FabianTerhorst** [comment]
Thanks alot.

**Comment by tphoney** [comment]
@FabianTerhorst @iameli https://github.com/drone-runners/drone-runner-exec/releases/tag/v1.0.0-beta.10 released ! 

thanks for your patience

**Pull request merged**
